name: ✨ 功能请求 | Feature Request
description: 建议新功能或改进现有工具 | Suggest a new feature or improvement for existing tools
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的建议！这有助于我们改进工具。
        Thanks for your suggestion! This helps us improve our tools.

  - type: dropdown
    id: request-type
    attributes:
      label: 请求类型 | Request Type
      description: 这是什么类型的请求？| What type of request is this?
      options:
        - 现有工具改进 | Improvement to existing tool
        - 全新工具 | Brand new tool
        - 用户界面改进 | UI/UX improvement
        - 性能优化 | Performance optimization
        - 其他 | Other
    validations:
      required: true

  - type: input
    id: tool-name
    attributes:
      label: 相关工具 | Related Tool
      description: 这个请求涉及哪个工具？| Which tool does this request relate to?
      placeholder: 例如：Base64编码器、或"新工具" | e.g., Base64 Encoder, or "New Tool"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题描述 | Problem Description
      description: 您遇到了什么问题，或者缺少什么功能？| What problem are you facing, or what functionality is missing?
      placeholder: |
        请描述：
        - 当前的限制或问题
        - 您希望实现的目标
        
        Please describe:
        - Current limitations or problems
        - What you want to achieve
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案 | Proposed Solution
      description: 您希望如何解决这个问题？| How would you like this problem to be solved?
      placeholder: |
        请详细描述您的建议：
        - 功能应该如何工作
        - 用户界面应该如何设计
        - 任何特殊要求
        
        Please describe your suggestion in detail:
        - How the feature should work
        - How the UI should be designed
        - Any special requirements
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案 | Alternatives
      description: 您考虑过其他解决方案吗？| Have you considered any alternative solutions?
      placeholder: 其他可能的方法... | Other possible approaches...

  - type: dropdown
    id: priority
    attributes:
      label: 优先级 | Priority
      description: 这个功能对您有多重要？| How important is this feature to you?
      options:
        - 非常重要 | Critical
        - 重要 | High
        - 中等 | Medium
        - 不急 | Low
    validations:
      required: true

  - type: checkboxes
    id: help
    attributes:
      label: 贡献意愿 | Contribution
      description: 您愿意帮助实现这个功能吗？| Would you be willing to help implement this feature?
      options:
        - label: 我可以提供更多需求细节 | I can provide more detailed requirements
        - label: 我可以帮助设计用户界面 | I can help design the user interface
        - label: 我可以帮助测试功能 | I can help test the feature
        - label: 我可以提供代码贡献 | I can contribute code
        - label: 我可以提供相关资源或文档 | I can provide relevant resources or documentation